### ISSUE TITLE
How to Add a new Fw

### ISSUE THREAD

**Issue by GiovanniVisentini** [STMicroelectronics-CentralLabs/STBlueDFU#4]
Hello, I want to replace the BlueNRG1_BLE_SensorDemo_Use_OTA_ServiceManager_v300.bin file with BLE_485.bin What should I do? Thank you.

_Originally posted by @xuezhanying in https://github.com/STMicroelectronics-CentralLabs/STBlueDFU/issues/1#issuecomment-453724242_

**Comment by GiovanniVisentini** [comment]
Hi Xue,

you have to add a new target item in this file:
https://github.com/STMicroelectronics-CentralLabs/STBlueDFU/blob/master/src/assets/fw_bin/blueOta.json

and copy the file inside the same directory.
rebuild the project
could be possible that you have to clean the db to see the new item.

Best Regards
Giovanni

**Comment by xuezhanying** [comment]
Ok, I have changed the bin file. Now I want to ask if the Chinese version of the OTA upgrade protocol is ready? This is how the bin file is sent to the text message of the Bluetooth device.

**Comment by GiovanniVisentini** [comment]
2-3 weeks means 15-20 days not 4..

it is faster for you understand python or translate only the chapter 2.1

**Comment by xuezhanying** [comment]
thank you

**Comment by xuezhanying** [comment]
Thank you very much, which country are you from?
